import { CostOfRawMaterial } from 'styles/Singularity/OwnerView/CafeManagement/RecipeManagement/index';

export const SET_LOADING = 'SET_LOADING';
export const SET_RAWMATERIALS = 'SET_RAWMATERIALS';
export const SET_BASICRECIPES = 'SET_BASICRECIPES';
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const UPDATE_SEARCHSTRING = 'UPDATE_SEARCHSTRING';
export const UPDATE_SEARCHRESULTS = 'UPDATE_SEARCHRESULTS';
export const CLEAR_SEARCHRESULTS = 'CLEAR_SEARCHRESULTS';
export const UPDATE_RAWMATERIALS = 'UPDATE_RAWMATERIALS';
export const REMOVE_RAWMATERIAL = 'REMOVE_RAWMATERIAL';
export const UPDATE_RAWMATERIALNAME = 'UPDATE_RAWMATERIALNAME';
export const UPDATE_RAWMATERIAL_PRICE = 'UPDATE_RAWMATERIAL_PRICE';
export const UPDATE_RAWMATERIAL_RATE = 'UPDATE_RAWMATERIAL_RATE';
export const UPDATE_RAWMATERIAL_COST = 'UPDATE_RAWMATERIAL_COST';
export const COMPLETE_FORM = 'COMPLETE_FORM';
export const SHOW_LOADER = 'SHOW_LOADER';
export const COMPLETE_RAWMATERIAL = 'COMPLETE_RAWMATERIAL';
export const SET_SEARCHFILTER = 'SET_SEARCHFILTER';
export const UPDATE_BASICRECIPE = 'UPDATE_BASICRECIPE';
export const UPDATE_BASICRECIPEUNITS = 'UPDATE_BASICRECIPEUNITS';
export const UPDATE_BASICRECIPEQUANTITY = 'UPDATE_BASICRECIPEQUANTITY';
export const UPDATE_BASICRECIPERAWMCOST = 'UPDATE_BASICRECIPERAWMCOST';
export const UPDATE_BASICRECIPERATE = 'UPDATE_BASICRECIPERATE';
export const REMOVE_BASICRECIPERM = 'REMOVE_BASICRECIPERM';
export const REMOVE_BASICRECIPE = 'REMOVE_BASICRECIPE';
export const SET_BASICRECIPERMSEARCHFILTER = 'SET_BASICRECIPERMSEARCHFILTER';
export const HANDLE_BASICRECIPESEARCHDISPLAY =
  'HANDLE_BASICRECIPESEARCHDISPLAY';
export const ADD_BASICRECCIPESEARCHRM = 'ADD_BASICRECCIPESEARCHRM';
export const SET_SAVEOPTION = 'SET_SAVEOPTION';
export const SET_RECIPES = 'SET_RECIPES';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const HANDLE_BASICRECIPEDISPLAY = 'HANDLE_BASICRECIPEDISPLAY';
export const HIDE_BASICRECIPERMONDELETE = 'HIDE_BASICRECIPERMONDELETE';
export const CALCULATE_RECIPERMQTYANDCOST = 'CALCULATE_RECIPERMQTYANDCOST';
export const CALCULATE_SINGLEBASICRECIPEQTYANDCOST =
  'CALCULATE_SINGLEBASICRECIPEQTYANDCOST';
export const CALCULATE_TOTALBASICRECIPERMQTYANDCOST =
  'CALCULATE_TOTALBASICRECIPERMQTYANDCOST';
export const INITIATE_BASICRECIPESSUBMISSION =
  'INITIATE_BASICRECIPESSUBMISSION';
export const BR_PREPARE_RAWMATERIALRATEUPDATE =
  'BR_PREPARE_RAWMATERIALRATEUPDATE';
export const BR_UPDATE_RAWMATERIALS = 'BR_UPDATE_RAWMATERIALS';
export const MAKE_BR_REQUEST = 'MAKE_BR_REQUEST';
export const RECIPE_PREPARE_RMBR_FORUPDATE = 'RECIPE_PREPARE_RMBR_FORUPDATE';
export const RECIPE_UPDATE_RAWMATERIALRATE = 'RECIPE_UPDATE_RAWMATERIALRATE';
export const MAKE_RECIPE_REQUEST = 'MAKE_RECIPE_REQUEST';
export const ANIMATE_BEFORE_EXIT = 'ANIMATE_BEFORE_EXIT';
export const REMOVE_ANIMATEBEFORE_EXIT = 'REMOVE_ANIMATEBEFORE_EXIT';
export const UPDATE_BASICRECIPE_BASEQUANTITY =
  'UPDATE_BASICRECIPE_BASEQUANTITY';
export const CREATE_RATEUPDATEDRM = 'CREATE_RATEUPDATEDRM';
export const CREATE_DEFAULTRMDATA = 'CREATE_DEFAULTRMDATA';
export const UPLOAD_DEFAULTRMDATA_COMPLETE = 'UPLOAD_DEFAULTRMDATA_COMPLETE';
export const TRANSFORM_RAWMATERIALS = 'TRANSFORM_RAWMATERIALS';
export const SET_NUMBER_OF_DEFULAT_RM_USED = 'SET_NUMBER_OF_DEFULAT_RM_USED';
export const INITIATE_TRIALFLOW = 'INITIATE_TRIALFLOW';
export const UPDATE_BASICRECIPE_BASEQTY = 'UPDATE_BASICRECIPE_BASEQTY';
export const RECIPE_UPDATE_DEFAULTRM = 'RECIPE_UPDATE_DEFAULTRM';
export const RECIPE_DEFAULTRM_UPLAODED = 'RECIPE_DEFAULTRM_UPLAODED';
export const RECIPE_DEFAULTRM_UPLAOD_COMPLETE =
  'RECIPE_DEFAULTRM_UPLAOD_COMPLETE';
export const TRIAL_TRANSFORM_BASIC_RECIPES = 'TRIAL_TRANSFORM_BASIC_RECIPES';
export const TRIAL_RECIPE_SET_BR_CHANGE = 'TRIAL_RECIPE_SET_BR_CHANGE';
export const TRIAL_RECIPE_SET_BR_NOCHANGE = 'TRIAL_RECIPE_SET_BR_NOCHANGE';
export const TRIAL_RECIPE_SETRM_QTYNAMECHANGE =
  'TRIAL_RECIPE_SETRM_QTYNAMECHANGE';
export const UPDATE_BASICRECIPERM_NAME = 'UPDATE_BASICRECIPERM_NAME';
export const TRIAL_BASIC_RECIPE_CHANGE_CHECK_COMPLETE =
  'TRIAL_BASIC_RECIPE_CHANGE_CHECK_COMPLETE';
export const TRIAL_RECIPE_UPDATE_CHANGEDBR = 'TRIAL_RECIPE_UPDATE_CHANGEDBR';
export const TRANSFORM_RECIPE_BASICRECIPES = 'TRANSFORM_RECIPE_BASICRECIPES';
