export const UPDATE_FIELD = 'UPDATE_FIELD';
export const COMPLETE_FORM = 'COMPLETE_FORM';
export const SET_LOADING = 'SET_LOADING';
export const SHOW_LOADER = 'SHOW_LOADER';
export const SET_USERID = 'SET_USERID';
export const SET_T = 'SET_T';
export const SET_MISSINGFIELDSERROR = 'SET_MISSINGFIELDSERROR';
export const REMOVE_MISSINGFIELDSERROR = 'REMOVE_MISSINGFIELDSERROR';
export const SET_SUPPLIERVALIDATIONS = 'SET_SUPPLIERVALIDATIONS';
export const SET_SUPPLIERVALIDATIONCOMPLETED =
  'SET_SUPPLIERVALIDATIONCOMPLETED';
export const INITIATE_POSTSUPPLIERREQUEST = 'INITIATE_POSTSUPPLIERREQUEST';
