export const defaultRawMaterialOPtion = [
  {
    name: 'default 100 gm solid',
    supplier: '5fef680ca43301322a3224e5',
    quantityInRecipe: 0,
    brandName: 'Benny',
    costOfRawMaterial: 0,
    _id: 'bennyRawMaterial',
    type: 'solid',
    baseQuantity: 100,
    baseUnit: 'gm',
    displayRateUnit: '100 gm',
    GSTPercent: 0,
    recipeUnit: 'gm',
    rate: 0
  },
  {
    name: 'default 500 gm solid',
    supplier: '5fef680ca43301322a3224e5',
    quantityInRecipe: 0,
    brandName: 'Benny',
    costOfRawMaterial: 0,
    _id: 'bennyRawMaterial',
    type: 'solid',
    baseQuantity: 500,
    baseUnit: 'gm',
    displayRateUnit: '500 gm',
    GSTPercent: 0,
    recipeUnit: 'gm',
    rate: 0
  },
  {
    name: 'default 1kg solid',
    supplier: '5fef680ca43301322a3224e5',
    quantityInRecipe: 0,
    brandName: 'Benny',
    costOfRawMaterial: 0,
    _id: 'bennyRawMaterial',
    type: 'solid',
    baseQuantity: 1000,
    baseUnit: 'gm',
    displayRateUnit: '1 kg',
    GSTPercent: 0,
    recipeUnit: 'gm',
    rate: 0
  },
  {
    name: 'default 100 mlliquid',
    supplier: '5fef680ca43301322a3224e5',
    quantityInRecipe: 0,
    brandName: 'Benny',
    costOfRawMaterial: 0,
    _id: 'bennyRawMaterial',
    type: 'liquid',
    baseQuantity: 100,
    baseUnit: 'ml',
    displayRateUnit: '100 ml',
    GSTPercent: 0,
    recipeUnit: 'ml',
    rate: 0
  },
  {
    name: 'default 500 mlliquid',
    supplier: '5fef680ca43301322a3224e5',
    quantityInRecipe: 0,
    brandName: 'Benny',
    costOfRawMaterial: 0,
    _id: 'bennyRawMaterial',
    type: 'liquid',
    baseQuantity: 500,
    baseUnit: 'ml',
    displayRateUnit: '500 ml',
    GSTPercent: 0,
    recipeUnit: 'ml',
    rate: 0
  },
  {
    name: 'default 1 lit liquid',
    supplier: '5fef680ca43301322a3224e5',
    quantityInRecipe: 0,
    brandName: 'Benny',
    costOfRawMaterial: 0,
    _id: 'bennyRawMaterial',
    type: 'liquid',
    baseQuantity: 1000,
    baseUnit: 'ml',
    displayRateUnit: '1 lit',
    GSTPercent: 0,
    recipeUnit: 'ml',
    rate: 0
  },
  {
    name: 'default type unit',
    supplier: '5fef680ca43301322a3224e5',
    quantityInRecipe: 0,
    brandName: 'Benny',
    costOfRawMaterial: 0,
    _id: 'bennyRawMaterial',
    type: 'unit',
    baseQuantity: 1,
    baseUnit: 'gm',
    displayRateUnit: '0 unit',
    GSTPercent: 0,
    recipeUnit: 'units',
    rate: 0
  }
];
